# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
     buildContext: '$(Build.SourcesDirectory)'
     containerRegistry: 'CoffeeFix Registry'
     repository: 'coffeefixconsole'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     tags: |
       $(tag)